# Sets the key which should activate the virtual layer so that your mappings are
# actually invoked when you press the specified target key combination.
# 
# Note: This program differentiates between "key" and "key combination" by
# wether a single key or multiple keys on the keyboard are pressed.
#
# For example the following wouldn't be a valid switch-key: "Shift+s"
#
# Warning: It also only deals with raw text (additionally to named keys such as
# "Ctrl", "Shift", "F1", etc.) which means "4" and "$" are not the same
# combination even though they share the same physical key. So it's possible to
# define "$" as "Shift+4" however this is strongly discouraged and you should
# rather use the actual character e. g. "$" wherever possible.
switch-key="CapsLock"

# This key combination will be simulated if you press and release the switch key
# without invoking any mappings.
default-simulation-combination="Escape"

# Autostart with the operating system
start-with-system = false

# All mappings are defined as "target key combination" and "replacement key
# combination" (The details about key combinations can be found at the top).
#
# Note: All target key combinations are additional to your switch key.
[mappings]
"h"="ArrowLeft"
"j"="ArrowDown"
"k"="ArrowUp"
"l"="ArrowRight"
"Ctrl+j"="PageDown"
"Ctrl+k"="PageUp"
"Shift+d"="Delete"
