# Sets the key which should activate the virtual layer so that your mappings are
# actually invoked when you press the specified target key combination.
#
# Following resource lists all possible named keys without the "VK" prefix.
# https://learn.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes
# 
# Note: This program differentiates between "key" and "key combination" by
# wether a single key or multiple distinct keys on the keyboard are pressed. 
# Each key combination can't be longer than four keys.
#
# For example the following wouldn't be a valid switch-key: "Shift+s"
#
# Warning: It also only deals with raw text (additionally to named keys such as
# "Ctrl", "Shift", "F1", etc.) which means "4" and "$" are not the same
# combination even though they share the same physical key. So it's possible to
# define "$" as "Shift+4" however this is strongly discouraged and you should
# rather use the actual character e. g. "$" wherever possible. The same isn't
# possible for alphabetic characters because the parser will see the upper case
# letter and try to find a special / named key with it instead e. g. "F" => 
# Search for keys that start with "F".
switch_key = "CapsLock"

# This key combination will be simulated if you press and release the switch key
# without invoking any mappings.
#
# Can be disabled by setting it to "".
default_simulation_combination = "Escape"

# Autostart with the operating system
start_with_system = "False"

# All mappings are defined as "target key combination" and "replacement key
# combination" (The details about key combinations can be found at the top).
#
# Note: All target key combinations are additional to your switch key.
[mappings]
"h" = "LeftArrow"
"j" = "DownArrow"
"k" = "UpArrow"
"l" = "RightArrow"
"Control+j" = "PageUp"
"Control+k" = "PageDown"
"Shift+d" = "Delete"
