# **switch_key**:
# 
# Sets the key which should activate the virtual layer so that your mappings are
# actually invoked when you press the specified target key combination.
#
# **List of named keys** 
#
# This list is based on https://learn.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes
# and was reduced as well as had some keys renamed to better fit the use case of
# this application (cross platform, confusing names, etc.).
#
# General
# - Escape
# - Tab
# - Space
# - Back
# - Return
# - CapsLock
# - LShift
# - RShift
# - LControl
# - RControl
# - LAlt
# - RAlt
# - LMeta (also known as left windows key)
# - RMeta (also known as right windows key)
#
# Extended keys (usually on the numpad when numlock off is and to the left of it)
# - LeftArrow
# - UpArrow
# - RightArrow
# - DownArrow
# - Clear
# - Insert
# - Delete
# - PageUp
# - PageDown
# - Scroll
# - Home
# - End
# - Sleep
# - Select
# - Execute
# - Help
# - Apps
# - Zoom
# - Print
# 
# Numpad
# - Numlock
# - Numpad0
# - Numpad1
# - Numpad2
# - Numpad3
# - Numpad4
# - Numpad5
# - Numpad6
# - Numpad7
# - Numpad8
# - Numpad9
# - Add
# - Subtract
# - Multiply
# - Divide
# - Separator
# - Decimal
#
# Function / application keys
# - F1
# - F2
# - F3
# - F4
# - F5
# - F6
# - F7
# - F8
# - F9
# - F10
# - F11
# - F12
# - F13
# - F14
# - F15
# - F16
# - F17
# - F18
# - F19
# - F20
# - F21
# - F22
# - F23
# - F24
# - Play
# - Pause
# - VolumeMute
# - VolumeDown
# - VolumeUp
# - MediaNextTrack
# - MediaPrevTrack
# - MediaStop
# - MediaPlayPause
# - BrowserBack
# - BrowserForward
# - BrowserRefresh
# - BrowserStop
# - BrowserSearch
# - BrowserFavorites
# - BrowserHome
# - LaunchMail
# - LaunchApp1
# - LaunchApp2
# 
# This program differentiates between "key" and "key combination" by wether a 
# single key or multiple distinct keys on the keyboard are pressed. For example
# "LShift+s" wouldn't be a valid switch-key.
#
# Warning: It also only deals with raw keys (additionally to named keys such as
# "Space", "Tab", "F1", etc.) which means a key combination that is defined
# with characters that require multiple keys to be pressed at the same time
# won't be recognized at all. An example would be "$" which you get by pressing
# "LShift+4" on most keyboard layouts. This likewise applies to all upper case
# letters (e. g "A", "B", "Ä", "Ö", etc.).
#
# There is no way for this application to inherently disallow specific
# characters such as "$" in a key combination while also staying compatible with
# most existing keyboard layouts.
switch_key = "CapsLock"

# **default_simulation_combination**:
#
# This key combination will be simulated if you press and release the switch key
# without invoking any mappings.
# 
# Note that each key combination can't be longer than four keys.
#
# Can be disabled by setting it to "".
default_simulation_combination = "Escape"

# **start_with_the_system**:
#
# Autostart with the operating system
#
# Only supported on windows because of the big amount of different things that
# can be done on unix systems to autostart and not wanting to impose a specific
# solution on the users.
start_with_system = "False"

# **mappings**:
#
# All mappings are defined as "target key combination" and "replacement key
# combination". See **switch_key** for the details about key combinations.
#
# Note: All target key combinations are additional to your switch key.
[mappings]
"h" = "LeftArrow"
"j" = "DownArrow"
"k" = "UpArrow"
"l" = "RightArrow"
"LControl+j" = "PageUp"
"LControl+k" = "PageDown"
"LShift+d" = "Delete"
